config/routes.rb
Rails.application.routes.draw do
  root "quizzes#index"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :quizzes, only: %i[index show] do
    resources :solved_quizzes, only: %i[create], module: :quizzes do
      post "guest_result", on: :member
    end
    resource :likes, only: %i[create destroy], module: :quizzes
    resources :comments, only: %i[index new create destroy], module: :quizzes
  end
  resources :users do
    resources :quizzes, module: :users do
      resources :quiz_options, only: %i[index new edit create update destroy], module: :quizzes
      resources :comments, only: %i[index], module: :quizzes
    end
    resources :solved_quizzes, only: %i[index], module: :users, module: :users
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :quizzes
    has_many :likes
    has_many :solved_quizzes
    has_many :comments
    validates :name, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    # 渡された文字列のハッシュ値を返す
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/quizzes/application_controller.rb
class Quizzes::ApplicationController < ApplicationController
    before_action :set_quiz

    private

    def set_quiz
        @quiz = Quiz.find(params[:quiz_id])
    end
end

app/controllers/quizzes/comments_controller.rb
class Quizzes::CommentsController < Quizzes::ApplicationController
    def index
        @comments = Comment.order(created_at: :desc)
    end

    def new
        @comment = current_user.comments.build
    end

    def create
        @comment = current_user.comments.build(comment_params.merge(quiz: @quiz))
        if @comment.save
            redirect_to quiz_comments_path(@quiz)
        else
            render :new
        end
    end

    def destroy
        @comment = current_user.comments.find(params[:id])
        @comment.destroy!
        redirect_to quiz_comments_path(@quiz)
    end

    def edit
        @comment = current_user.comments.find(params[:id])
    end

    def update
        @comment = current_user.comments.find(params[:id])
        if @comment.update(comment_params)
            redirect_to quiz_comment_path(@quiz, @comment)
        else
            render :edit
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/quizzes/likes_controller.rb
class Quizzes::LikesController < Quizzes::ApplicationController
    def create
        @like = current_user.likes.build(quiz: @quiz)
        @like.save!
        redirect_to root_path
    end

    def destroy
        @like = current_user.likes.find_by(quiz: @quiz)
        @like.destroy!
        redirect_to root_path
    end
end

app/controllers/quizzes/solved_quizzes_controller.rb
class Quizzes::SolvedQuizzesController < Quizzes::ApplicationController
    def create
        @solved_quiz = @quiz.solved_quizzes.build(solved_quiz_params.merge(user_id: current_user.id))
        @solved_quiz.save!
        @result = @solved_quiz.quiz_option.correct
        respond_to do |format|
            format.turbo_stream { render turbo_stream: turbo_stream.replace("result_frame", partial: "quizzes/result", locals: { result: @result }) }
        end
    end

    # todo 非ログインユーザーでも解答出来るように
    def guest_result
        selected_answer = @quiz.quiz_options.find(params[:solved_quiz][:quiz_option_id])
        @result = selected_answer.correct
        respond_to do |format|
            format.turbo_stream { render turbo_stream: turbo_stream.replace("result_frame", partial: "quizzes/result", locals: { result: @result }) }
        end
    end

    private

    def solved_quiz_params
        params.require(:solved_quiz).permit(:quiz_option_id)
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
    def index
        how_sort = sort_params[:sort]
        if how_sort == "desc"
            @quizzes = Quiz.order(created_at: :desc)
        elsif how_sort == "like"
            @quizzes = Quiz.like_desc
        elsif how_sort == "buzz1d"
            @quizzes = Quiz.like_desc.where(created_at: (1.days.ago)..(Time.now))
        else
            @quizzes = Quiz.order(created_at: :desc)
        end
    end

    def show
        @quiz = Quiz.find(params[:id])
        @solved_quiz = @quiz.solved_quizzes.build
    end

    private

    def sort_params
        params.permit(:sort)
    end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
    before_action :set_user

    private

    def set_user
        @user = User.find(current_user.id)
    end
end

app/controllers/users/quizzes/application_controller.rb
class Users::Quizzes::ApplicationController < Users::ApplicationController
    before_action :set_quiz

    private

    def set_quiz
        @quiz = @user.quizzes.find(params[:quiz_id])
    end
end

app/controllers/users/quizzes/comments_controller.rb
class Users::Quizzes::CommentsController < Users::Quizzes::ApplicationController
  def index
  @comments = @quiz.comments.order(created_at: :desc)
  end
end

app/controllers/users/quizzes/quiz_options_controller.rb
class Users::Quizzes::QuizOptionsController < Users::Quizzes::ApplicationController
    before_action :set_quiz_option, only: [ :edit, :update, :destroy ]

    def index
        @quiz_options = @quiz.quiz_options
    end

    def new
        @quiz_option = @quiz.quiz_options.build
    end

    def create
        @quiz_option = @quiz.quiz_options.build(quiz_option_params)
        if @quiz_option.save
            redirect_to user_quiz_path(current_user, @quiz)
        else
            # フラッシュの文
            render :new
        end
    end

    def edit
    end

    def update
        if @quiz_option.update(quiz_option_params)
            redirect_to user_quiz_path(current_user, @quiz)
        else
            # フラッシュ文
            render :edit
        end
    end

    def destroy
        @quiz_option.destroy!
        # フラッシュ文
        redirect_to user_quiz_path(current_user, @quiz)
    end

    private
    def quiz_option_params
        params.require(:quiz_option).permit(:correct, :content)
    end

    def set_quiz_option
        @quiz_option = @quiz.quiz_options.find(params[:id])
    end
end

app/controllers/users/quizzes_controller.rb
class Users::QuizzesController < Users::ApplicationController
    def index
        @quizzes = @user.quizzes.order(created_at: :desc)
    end

    def show
        @quiz = Quiz.find(params[:id])
        @quiz_options = @quiz.quiz_options
    end

    def new
        @quiz = @user.quizzes.build
        4.times { @quiz.quiz_options.build }
    end

    def create
        @quiz = @user.quizzes.build(quiz_params)
        if @quiz.save
            redirect_to user_quizzes_path(@user), notice: "クイズを作成しました"
        else
            render :new
        end
    end

    def destroy
        @quiz = @user.quizzes.find(params[:id])
        @quiz.destroy!
        redirect_to user_quizzes_path(@user), notice: "クイズを削除しました"
    end

    def edit
        @quiz = @user.quizzes.find(params[:id])
    end

    def update
        @quiz = @user.quizzes.find(params[:id])
        if @quiz.update(quiz_params)
            redirect_to user_quiz_path(@quiz), notice: "クイズを更新しました"
        else
            render :edit
        end
    end

    private
    def quiz_params
        params.require(:quiz).permit(
            :title, :content, :hint, :explanation,
            quiz_options_attributes: [ :id, :content, :correct, :_destroy ]
        )
    end
end

app/controllers/users/solved_quizzes_controller.rb
class Users::SolvedQuizzesController < Users::ApplicationController
    def index
        @solved_quizzes = @user.solved_quizzes.order(created_at: :desc)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      redirect_to root_path, notice: "アカウントを作成しました"
    else
      render "new", status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/quizzes/_form.html.erb
<div class="mb-3 text-light">
    <%= form.label :title, "タイトル" %>
    <div>
        <%= form.text_field :title, class: "form-control w-auto", :style => "resize: none;", placeholder: "タイトル" %>
    </div>
</div>
<div class="mb-3 text-light">
    <%= form.label :content, "問題文" %>
    <div>
        <%= form.text_area :content, class: "form-control", placeholder: "問題文" %>
    </div>
</div>
<div class="mb-3 text-light">
    <%= form.label :explanation, "答えの解説" %>
    <div>
        <%= form.text_area :explanation, class: "form-control", placeholder: "解説文" %>
    </div>
</div>

app/views/users/quizzes/edit.html.erb
<div class="p-3">
    <div class="card bg-dark">
        <div class="card-body">
            <h5 class="card-title mt-3 fw-bold fs-4 text-light">クイズを編集</h5>
            <%= form_with(model: [@user, @quiz]) do |f| %>
                <%= render 'form', form: f %>
                <%= f.submit "クイズを編集", class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/quizzes/index.html.erb
<div class="p-3">
    <div class="card border-gray-background" style="margin: 0 auto;">
        <div class="card-body">
            <h5 class="card-title mt-3 fw-bold fs-2 text-white" style="text-align: left; width: 90%; margin: 0 auto;">クイズ一覧</h5>
            <div class="my-5">
                <ul class="list-group">
                    <% @quizzes.each do |quiz| %>
                        <li class="list-group-item mb-3 border-3 border-dark d-flex justify-content-between align-items-center", style="width: 90%; margin: 0 auto;">
                            <%= link_to user_quiz_path(current_user, quiz), class: 'fw-bold fs-4 text-dark text-decoration-none d-flex justify-content-between w-100' do %>
                                <%= quiz.title %>
                            <% end %>
                    
                            <%= link_to user_quiz_comments_path(current_user, quiz), class: 'text-decoration-none', aria: { label: "コメントを見る" } do %>
                                <i class="fa-regular fa-comment-dots fs-3 comment-dot-icon-color"></i>
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/users/quizzes/new.html.erb
<div class="p-3">
  <div class="card bg-dark">
    <div class="card-body">
      <h5 class="card-title mt-3 fw-bold fs-4 text-light">クイズを作成</h5>
      <%= form_for [@user, @quiz], data: { turbo: false } do |f| %>
        <% if @quiz.errors.any? %>
            <div class="alert alert-danger">
                <ul class="mb-0">
                <% @quiz.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                </ul>
            </div>
        <% end %>
        <%= render 'form', form: f %>
        <%= f.fields_for :quiz_options do |quiz_option| %>
        <li class="list-group-item mb-3 border-4 border-dark">
          <%= quiz_option.label :correct, class: "text-white" do %>
            <i class="fa-regular fa-circle text-success"></i>
          <% end %>
          <%= quiz_option.radio_button :correct, true %>
          <%= quiz_option.label :correct, class: "text-white" do %>
            <i class="fa-solid fa-xmark text-danger"></i>
          <% end %>
          <%= quiz_option.radio_button :correct, false, checked: true %>
          <%= quiz_option.text_field :content, placeholder: "選択肢" %>
        </li>
        <% end %>
      <%= f.submit "クイズを投稿", class: "btn btn-primary float-end" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/quizzes/show.html.erb
<div class="p-3">
    <div class="card border-gray-background shadow-sm">
        <div class="card-body" style="width: 90%; margin: 0 auto;">
            <div class="mt-3 mb-5">
                <%= link_to user_quizzes_path(current_user), class: "large-white-text" do %>
                    <i class="fa-solid fa-arrow-left"></i> クイズ一覧
                <% end %>
            </div>
            <div class="d-flex justify-content-between align-items-start mb-3">
                <div>
                    <h3 class="fw-bold fs-2 text-white mb-5">クイズ詳細</h3>
                    <h4 class="fw-bold fs-2" style="color: #ffffff"><%= @quiz.title %></h4>
                </div>
                <div class="d-flex gap-2">
                    <%= link_to "編集", edit_user_quiz_path(current_user, @quiz), class: 'btn btn-sm btn-outline-primary white-background' %>
                    <%= button_to "削除", user_quiz_path(current_user, @quiz), method: :delete, form: { class: 'd-inline' }, data: { turbo_confirm: "削除してよろしいですか？" }, class: 'btn btn-sm btn-outline-danger white-background' %>
                </div>
            
            
            
            </div>
            <div class="card bg-light mb-3">
                <div class="card-body">
                    <h5 class="card-title fw-bold">問題</h5>
                    <p class="card-text"><%= @quiz.content %></p>
                </div>
            </div>
            <div class="card bg-light border mb-4">
                <div class="card-body">
                    <h5 class="card-title fw-bold">解説</h5>
                    <p class="card-text"><%= @quiz.explanation %></p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <h5 class="fw-bold fs-5 text-white m-0">選択肢一覧</h5>
                <%= link_to "選択肢追加", new_user_quiz_quiz_option_path(current_user, @quiz), 
                      class: 'btn btn-outline-success mt-3 white-background' %>
            </div>
            <div class="mb-4">
                    <% @quiz_options.each do |option| %>
                        <div class="card border-0 shadow-sm mb-3">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <div class="d-flex align-items-center gap-2">
                                        <% if option.correct %>
                                            <span class="badge bg-success px-2">正解</span>
                                        <% else %>
                                            <span class="badge bg-danger px-2">不正解</span>
                                        <% end %>
                                        <p class="m-0"><%= option.content %></p>
                                    </div>
                                    <div class="btn-group btn-group-sm" role="group" aria-label="選択肢の操作">
                                        <%= link_to edit_user_quiz_quiz_option_path(current_user, @quiz, option), 
                                            class: 'btn btn-outline-primary',
                                            title: '選択肢を編集する',
                                            aria: { label: '選択肢を編集する' } do %>
                                            <i class="fa-solid fa-pen-to-square"></i>
                                        <% end %>
                                        <%= button_to user_quiz_quiz_option_path(current_user, @quiz, option), 
                                            method: :delete, 
                                            form: { class: 'd-inline' },
                                            data: { turbo_confirm: "削除してよろしいですか？" },
                                            class: 'btn btn-outline-danger',
                                            title: '選択肢を削除する',
                                            aria: { label: '選択肢を削除する' } do %>
                                            <i class="fa-solid fa-trash"></i>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% if @quiz_options.any? == false %>
                    <div class="alert alert-info">
                        選択肢がありません
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>