config/routes.rb
Rails.application.routes.draw do
  root "quizzes#index"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :quizzes, only: %i[index show] do
    resources :solved_quizzes, only: %i[create], module: :quizzes do
      post "guest_result", on: :member
    end
    resource :likes, only: %i[create destroy], module: :quizzes
    resources :comments, only: %i[index new create destroy], module: :quizzes
  end
  resources :users do
    resources :quizzes, module: :users do
      resources :quiz_options, only: %i[index new edit create update destroy], module: :quizzes
      resources :comments, only: %i[index], module: :quizzes
    end
    resources :solved_quizzes, only: %i[index], module: :users, module: :users
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/quizzes/application_controller.rb
class Quizzes::ApplicationController < ApplicationController
    before_action :set_quiz

    private

    def set_quiz
        @quiz = Quiz.find(params[:quiz_id])
    end
end

app/controllers/quizzes/comments_controller.rb
class Quizzes::CommentsController < Quizzes::ApplicationController
    def index
        @comments = Comment.order(created_at: :desc)
    end

    def new
        @comment = current_user.comments.build
    end

    def create
        @comment = current_user.comments.build(comment_params.merge(quiz: @quiz))
        if @comment.save
            redirect_to quiz_comments_path(@quiz)
        else
            render :new
        end
    end

    def destroy
        @comment = current_user.comments.find(params[:id])
        @comment.destroy!
        redirect_to quiz_comments_path(@quiz)
    end

    def edit
        @comment = current_user.comments.find(params[:id])
    end

    def update
        @comment = current_user.comments.find(params[:id])
        if @comment.update(comment_params)
            redirect_to quiz_comment_path(@quiz, @comment)
        else
            render :edit
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/quizzes/likes_controller.rb
class Quizzes::LikesController < Quizzes::ApplicationController
    def create
        @like = current_user.likes.build(quiz: @quiz)
        @like.save!
        redirect_to root_path
    end

    def destroy
        @like = current_user.likes.find_by(quiz: @quiz)
        @like.destroy!
        redirect_to root_path
    end
end

app/controllers/quizzes/solved_quizzes_controller.rb
class Quizzes::SolvedQuizzesController < Quizzes::ApplicationController
    def create
        @solved_quiz = @quiz.solved_quizzes.build(solved_quiz_params.merge(user_id: current_user.id))
        @solved_quiz.save!
        @result = @solved_quiz.quiz_option.correct
        respond_to do |format|
            format.turbo_stream { render turbo_stream: turbo_stream.replace("result_frame", partial: "quizzes/result", locals: { result: @result }) }
        end
    end

    # todo 非ログインユーザーでも解答出来るように
    def guest_result
        selected_answer = @quiz.quiz_options.find(params[:solved_quiz][:quiz_option_id])
        @result = selected_answer.correct
        respond_to do |format|
            format.turbo_stream { render turbo_stream: turbo_stream.replace("result_frame", partial: "quizzes/result", locals: { result: @result }) }
        end
    end

    private

    def solved_quiz_params
        params.require(:solved_quiz).permit(:quiz_option_id)
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
    def index
        how_sort = sort_params[:sort]
        if how_sort == "desc"
            @quizzes = Quiz.order(created_at: :desc)
        elsif how_sort == "like"
            @quizzes = Quiz.like_desc
        elsif how_sort == "buzz1d"
            @quizzes = Quiz.like_desc.where(created_at: (1.days.ago)..(Time.now))
        else
            @quizzes = Quiz.order(created_at: :desc)
        end
    end

    def show
        @quiz = Quiz.find(params[:id])
        @solved_quiz = @quiz.solved_quizzes.build
    end

    private

    def sort_params
        params.permit(:sort)
    end
end

app/controllers/users/quizzes/application_controller.rb
class Users::Quizzes::ApplicationController < Users::ApplicationController
    before_action :set_quiz

    private

    def set_quiz
        @quiz = @user.quizzes.find(params[:quiz_id])
    end
end

app/controllers/users/quizzes/comments_controller.rb
class Users::Quizzes::CommentsController < Users::Quizzes::ApplicationController
  def index
  @comments = @quiz.comments.order(created_at: :desc)
  end
end

app/controllers/users/quizzes/quiz_options_controller.rb
class Users::Quizzes::QuizOptionsController < Users::Quizzes::ApplicationController
    before_action :set_quiz_option, only: [ :edit, :update, :destroy ]

    def index
        @quiz_options = @quiz.quiz_options
    end

    def new
        @quiz_option = @quiz.quiz_options.build
    end

    def create
        @quiz_option = @quiz.quiz_options.build(quiz_option_params)
        if @quiz_option.save
            redirect_to user_quiz_path(current_user, @quiz)
        else
            # フラッシュの文
            render :new
        end
    end

    def edit
    end

    def update
        if @quiz_option.update(quiz_option_params)
            redirect_to user_quiz_path(current_user, @quiz)
        else
            # フラッシュ文
            render :edit
        end
    end

    def destroy
        @quiz_option.destroy!
        # フラッシュ文
        redirect_to user_quiz_path(current_user, @quiz)
    end

    private
    def quiz_option_params
        params.require(:quiz_option).permit(:correct, :content)
    end

    def set_quiz_option
        @quiz_option = @quiz.quiz_options.find(params[:id])
    end
end

app/controllers/users/quizzes_controller.rb
class Users::QuizzesController < Users::ApplicationController
    def index
        @quizzes = @user.quizzes.order(created_at: :desc)
    end

    def show
        @quiz = Quiz.find(params[:id])
        @quiz_options = @quiz.quiz_options
    end

    def new
        @quiz = @user.quizzes.build
        4.times { @quiz.quiz_options.build }
    end

    def create
        @quiz = @user.quizzes.build(quiz_params)
        if @quiz.save
            redirect_to user_quizzes_path(@user), notice: "クイズを作成しました"
        else
            render :new
        end
    end

    def destroy
        @quiz = @user.quizzes.find(params[:id])
        @quiz.destroy!
        redirect_to user_quizzes_path(@user), notice: "クイズを削除しました"
    end

    def edit
        @quiz = @user.quizzes.find(params[:id])
    end

    def update
        @quiz = @user.quizzes.find(params[:id])
        if @quiz.update(quiz_params)
            redirect_to user_quiz_path(@quiz), notice: "クイズを更新しました"
        else
            render :edit
        end
    end

    private
    def quiz_params
        params.require(:quiz).permit(
            :title, :content, :hint, :explanation,
            quiz_options_attributes: [ :id, :content, :correct, :_destroy ]
        )
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_index_sort_button.html.erb
<div class="d-flex justify-content-end pb-3 pe-2">
        <div class="dropdown me-1">
            <% sort_options = { "desc" => "新着順", "like" => "いいね順", "buzz1d" => "いいね順(1日以内)" } %>
            <% selected_sort = sort_options[params[:sort]] || "新着順" %>
            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-bs-offset="10,20">
                <%= selected_sort %>
            </button>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to root_path(sort: "desc"), method: :get, class: "dropdown-item" do %>
                        新着順
                    <% end %>
                </li>
                <li>
                    <%= link_to root_path(sort: "like"), method: :get, class: "dropdown-item" do %>
                        いいね順
                    <% end %>
                </li>
                <li>
                    <%= link_to root_path(sort: "buzz1d"), method: :get, class: "dropdown-item" do %>
                        いいね順(1日以内)
                    <% end %>
                </li>
            </ul>
        </div>
    </div>

app/views/quizzes/_result.html.erb
<div id="result_frame" class="<%= @result ? 'celebrate' : 'not-celebrate' %>">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card text-white">
          <div class="card-body px-5">
            <h5 class="card-title text-center pb-3">
              <%= @result ? "正解" : "不正解" %>
            </h5>
            <div class="d-flex justify-content-around">
              <% if current_user %>
                <%= link_to "解いたクイズ一覧", user_solved_quizzes_path(current_user), remote: true, class: "btn nav-link" %>
              <% end %>
              <%= link_to '問題一覧に戻る', root_url, class: "btn nav-link d-inline-block w-auto px-3" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card explanation-card">
        <div class="card-body">
          <h3 class="card-title text-center">解説</h3>
          <p class="card-text text-center">
            <%= @quiz.explanation %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quizzes/_show_quiz.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card bg-dark text-white">
        <div class="card-body px-5">
          <h5 class="card-title text-center"><%= @quiz.content %></h5>
          <%= turbo_frame_tag "quiz_result_#{@quiz.id}" do %>
            <%= form_with(model: @solved_quiz, url: current_user ? quiz_solved_quizzes_path(@quiz) : guest_result_quiz_solved_quiz_path(@quiz), method: :post, data: { turbo_frame: "quiz_result_#{@quiz.id}"} ) do |f| %>
            <div data-controller="collapse">
                <button
                    type="button"
                    data-action="click->collapse#toggle"
                    class="btn btn-info mb-3"
                >
                選択肢を表示する
              </button>
              
              <ul class="list-group list-group-flush gap-3">
              <div 
                  data-collapse-target="content"
                  class="mt-3 d-none"
              >

              <ul class="list-group list-group-flush gap-3">
                <% @quiz.quiz_options.shuffle.each_with_index do |option, index| %>
                    <li class="list-group-item bg-secondary text-white rounded mb-2">
                    <div class="form-check">
                        <%= f.radio_button :quiz_option_id, option.id, class: "form-check-input", id: "option-#{option.id}", checked: (index == 0) %>
                        <%= f.label :quiz_option_id, option.content, class: "form-check-label", for: "option-#{option.id}" %>
                    </div>
                    </li>
                <% end %>
                </ul>
                <%= f.submit "解答する", class: "btn btn-primary mt-3" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quizzes/index.html.erb
<div class="p-5">
    <%= render 'quizzes/index_sort_button' %>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <% @quizzes.each do |quiz| %>
            <% if quiz.quiz_options.present? %>
                <div class="col">
                    <div class="card px-3 card-base-color">
                        <div class="card-body">
                            <h5 class="card-title mb-2 d-flex justify-content-center"><%= quiz.title %></h5>
                            <h6 class="card-subtitle d-flex justify-content-end text-body-secondary">作成者:<%= quiz.user.name %></h6>
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <%= link_to quiz_path(quiz) do %>
                                        <button type="button" class="btn btn-light">挑戦する</button>
                                    <% end %>
                                </div>
                                <div>
                                    <div class="d-flex align-items-center">
                                        <% if current_user %>
                                            <div>
                                                <% if current_user.likes.find_by(quiz: quiz).present? %>
                                                    <%= button_to quiz_likes_path(quiz), class: "btn btn-link" , method: :delete do %>
                                                        <i class="fa-solid fa-heart heart-liked-icon-color"></i>
                                                    <% end %>
                                                <% else %>
                                                    <%= button_to quiz_likes_path(quiz), class: "btn btn-link" , method: :post do %>
                                                        <i class="fa-regular fa-heart heart-liked-icon-color"></i>
                                                    <% end %>
                                                <% end %>
                                            </div>
                                        <% else %>
                                            <div class="icon-padding">
                                                <i class="fa-solid fa-heart heart-icon-color"></i>
                                            </div>
                                        <% end %>
                                        <div>
                                            <%= quiz.likes.count %>
                                        </div>
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <% if current_user %>
                                            <div>
                                                <%= link_to new_quiz_comment_path(quiz), class: 'btn btn-link' do %>
                                                    <i class="fa-regular fa-comment-dots comment-dot-icon-color"></i> 
                                                <% end %>
                                            </div>
                                        <% else %>
                                            <div class="icon-padding">
                                                <i class="fa-regular fa-comment-dots comment-dot-icon-color"></i>
                                            </div>
                                        <% end %>
                                        <div>
                                            <%= quiz.comments.count %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/quizzes/show.html.erb
<div id="result_frame">
    <p id="result_text">
        <%= render 'quizzes/show_quiz' %>
    </p>
</div>