config/routes.rb
Rails.application.routes.draw do
  root "quizzes#index"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :quizzes, only: %i[index show] do
    resources :solved_quizzes, only: %i[create], module: :quizzes do
      post "guest_result", on: :member
    end
    resource :likes, only: %i[create destroy], module: :quizzes
    resources :comments, only: %i[index new create destroy], module: :quizzes
  end
  resources :users do
    resources :quizzes, module: :users do
      resources :quiz_options, only: %i[index new edit create update destroy], module: :quizzes
      resources :comments, only: %i[index], module: :quizzes
    end
    resources :solved_quizzes, only: %i[index], module: :users, module: :users
  end
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_footer.html.erb
<footer class="text-black fw-semibold">
  © 2025 プロテインシェイカーズ
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header">
    <%= link_to 'BUZZAR', root_path, class: 'logo' %>
    <nav>
      <% if current_user %>
        <%= link_to 'クイズを投稿', new_user_quiz_path(current_user), class: 'nav-link' %>
        <%= link_to 'ユーザー情報', user_path(current_user), class: 'nav-link' %>
        <%= link_to '作成済みクイズを閲覧', user_quizzes_path(current_user), class: 'nav-link' %>
        <%= link_to '回答履歴', user_solved_quizzes_path(current_user), class: 'nav-link' %>
        <%= button_to 'ログアウト', logout_path, class: 'btn nav-link', method: :delete %>
      <% end %>
      <% if !current_user %>
        <%= link_to 'ログイン', login_path, class: 'nav-link' %>
        <%= link_to '登録', signup_path, class: 'nav-link' %>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BUZZAR</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= render 'partial/flash' %>
  <div class="content">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>